const companyTransferData = [
    {
        id: 1,
        name: '南京**商贸有限公司',
        price: '1.10万',
        priceRange: '1万-2万',
        industry: '贸易类',
        type: '有限责任公司',
        time: '1-2年',
        tax: '一般纳税人',
        capital: '100-500万',
        region: '华东地区',
        date: '今日发布',
        yearRegistration: '2017',
        address: '江西 西昌 西湖区'
    },
    {
        id: 2,
        name: '**贷款代理（东莞）有限公司',
        price: '2.50万',
        priceRange: '2万-5万',
        industry: '金融类',
        type: '个人独资公司',
        time: '1年以下',
        tax: '小规模',
        capital: '50万以下',
        region: '华南地区',
        date: '今日发布',
        yearRegistration: '2019',
        address: '广东 东莞 长安镇'
    },
    {
        id: 3,
        name: '四川**汽车服务有限公司',
        price: '0.6万',
        priceRange: '1万以下',
        industry: '服务类',
        type: '有限责任公司',
        time: '1年以下',
        tax: '未核税',
        capital: '100-500万',
        region: '西南地区',
        date: '今日发布',
        yearRegistration: '2018',
        address: '四川 成都 武侯区'
    },
    {
        id: 4,
        name: '北京**国际文化有限公司',
        price: '1.30万',
        priceRange: '1万-2万',
        industry: '设计/策划类',
        type: '有限责任公司',
        time: '2-3年',
        tax: '小规模',
        capital: '100-500万',
        region: '华北地区',
        date: '今日发布',
        yearRegistration: '2016',
        address: '北京 北京 通州区'
    },
    {
        id: 5,
        name: '苏州**热处理有限公司',
        price: '475万',
        priceRange: '10万以上',
        industry: '产品类',
        type: '有限责任公司',
        time: '3年以上',
        tax: '一般纳税人',
        capital: '50-100万',
        region: '华东地区',
        date: '今日发布',
        yearRegistration: '2007',
        address: '江苏 苏州 相城区'
    },
    {
        id: 6,
        name: '北京**生物科技有限公司',
        price: '2.25万',
        priceRange: '2万-5万',
        industry: '科技类',
        type: '个人独资公司',
        time: '3年以上',
        tax: '小规模',
        capital: '50-100万',
        region: '华北地区',
        date: '今日发布',
        yearRegistration: '2008',
        address: '北京 北京 昌平区'
    },
    {
        id: 7,
        name: '上海**保洁服务有限公司',
        price: '0.6万',
        priceRange: '1万以下',
        industry: '服务类',
        type: '有限责任公司',
        time: '1年以下',
        tax: '小规模',
        capital: '1000万以上',
        region: '华东地区',
        date: '今日发布',
        yearRegistration: '2019',
        address: '上海 上海 奉贤区'
    },
    {
        id: 8,
        name: '上海**物业管理有限公司',
        price: '0.9万',
        priceRange: '1万以下',
        industry: '管理类',
        type: '有限责任公司',
        time: '3年以上',
        tax: '小规模',
        capital: '500-1000万',
        region: '华东地区',
        date: '今日发布',
        yearRegistration: '2014',
        address: '上海 上海 奉贤区'
    },
    {
        id: 9,
        name: '宁夏**网络科技有限公司',
        price: '1.30万',
        priceRange: '1万-2万',
        industry: '科技类',
        type: '个人独资公司',
        time: '1-2年',
        tax: '小规模',
        capital: '100-500万',
        region: '西北地区',
        date: '今日发布',
        yearRegistration: '2018',
        address: '宁夏 银川 金凤区'
    },
    {
        id: 10,
        name: '上海**电子科技有限公司',
        price: '1.00万',
        priceRange: '1万-2万',
        industry: '科技类',
        type: '有限责任公司',
        time: '2-3年',
        tax: '一般纳税人',
        capital: '50-100万',
        region: '华东地区',
        date: '今日发布',
        yearRegistration: '2016',
        address: '上海 上海 金山区'
    },
    {
        id: 11,
        name: '成都**网络科技有限公司',
        price: '0.8万',
        priceRange: '1万以下',
        industry: '科技类',
        type: '有限责任公司',
        time: '1年以下',
        tax: '小规模',
        capital: '100-500万',
        region: '西南地区',
        date: '今日发布',
        yearRegistration: '2018',
        address: '四川 成都 金牛区'
    },
    {
        id: 12,
        name: '**劳务派遣(上海)有限公司',
        price: '4.38万',
        priceRange: '2万-5万',
        industry: '人才类',
        type: '有限责任公司',
        time: '1年以下',
        tax: '小规模',
        capital: '100-500万',
        region: '华东地区',
        date: '今日发布',
        yearRegistration: '2019',
        address: '上海 上海 崇明区'
    }
]